# generated by zon2nix (https://github.com/jcollie/zon2nix)
{
  lib,
  fetchgit,
  fetchurl,
  fetchzip,
  runCommandLocal,
  zig_0_16,
  zstd,
  name ? "zig-packages",
  # Accepted and ignored. Expressions from zon2nix before 0.8 built the
  # packages with `linkFarm`, and some callers override it with a version that
  # copies, to work around Zig mishandling symlinked package directories
  # (https://codeberg.org/ziglang/zig/issues/32121). The packages are real
  # directories now, so the override is not needed, and is taken here only so
  # that passing it is not an error.
  linkFarm ? null,
}: let
  # A git repository, checked out the way Zig reads it: every file as
  # committed. An ordinary checkout applies the repository's `.gitattributes`,
  # which can rewrite a file's line endings or run it through a filter, and
  # the package would then no longer match its hash. Pointing git at its
  # built-in empty tree for attributes turns them all off, and `core.autocrlf`
  # is turned off too, since it converts line endings even without them.
  # zon2nix computes the hash with exactly these settings.
  fetchZigGit = args:
    fetchgit (
      args
      // {
        fetchSubmodules = false;
        preFetch = ''
          export GIT_ATTR_SOURCE=4b825dc642cb6eb9a060e54bf8d69288fbee4904
          export GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=core.autocrlf GIT_CONFIG_VALUE_0=false
        '';
      }
    );

  # Every package, by the hash Zig knows it by, as Nix fetches it.
  packages = {
    "aro-0.0.0-JSD1Qk6lNgDdcDV4Vh7Sfy-34m2TluIVOdPzMmj_0BjX" = fetchzip {
      name = "aro";
      url = "https://github.com/vancluever/arocc/archive/f97cdfc3779aec4b242299e2fc9a1c828c3547c6.tar.gz";
      hash = "sha256-G/NNgk7KhJSLdy17ip1igIzpYhAUlzO7ef8r3/iCv/s=";
    };
    "N-V-__8AANT61wB--nJ95Gj_ctmzAtcjloZ__hRqNw5lC1Kr" = fetchurl {
      url = "https://deps.files.ghostty.org/DearBindings_v0.17_ImGui_v1.92.5-docking.tar.gz";
      hash = "sha256-i/7FAOAJJvZ5hT7iPWfMOS08MYFzPKRwRzhlHT9wuqM=";
    };
    "N-V-__8AALw2uwF_03u4JRkZwRLc3Y9hakkYV7NKRR9-RIZJ" = fetchzip {
      name = "breakpad";
      url = "https://deps.files.ghostty.org/breakpad-b99f444ba5f6b98cac261cbb391d8766b34a5918.tar.gz";
      hash = "sha256-Pro7cOujfdYAc3REK6HDyi/tlyH+Sq5Yt/OjQ0lg4FE=";
    };
    "N-V-__8AAOgqbADacob-q2_DMQlmgaG4xKHRuW-6PJ4oJzMZ" = fetchzip {
      name = "fontconfig";
      url = "https://gitlab.freedesktop.org/api/v4/projects/890/packages/generic/fontconfig/2.18.3/fontconfig-2.18.3.tar.xz";
      hash = "sha256-fAe2C2MdhrVb12K8LBaUPU/OyWpulHpMsnarkuLHWS4=";
    };
    "N-V-__8AAKLKpwC4H27Ps_0iL3bPkQb-z6ZVSrB-x_3EEkub" = fetchzip {
      name = "freetype";
      url = "https://deps.files.ghostty.org/freetype-1220b81f6ecfb3fd222f76cf9106fecfa6554ab07ec7fdc4124b9bb063ae2adf969d.tar.gz";
      hash = "sha256-Io9k8xmOKrk+4GSi3PUU60X68T4BpG8dru1/KO+jVRk=";
    };
    "N-V-__8AADcZkgn4cMhTUpIz6mShCKyqqB-NBtf_S2bHaTC-" = fetchzip {
      name = "gettext";
      url = "https://deps.files.ghostty.org/gettext-0.24.tar.gz";
      hash = "sha256-FBb80LX5WtgB9O32HRhg9g8aQSyOmsFW8qonySSlaO4=";
    };
    "N-V-__8AABzkUgISeKGgXAzgtutgJsZc0-kkeqBBscJgMkvy" = fetchzip {
      name = "glslang";
      url = "https://deps.files.ghostty.org/glslang-12201278a1a05c0ce0b6eb6026c65cd3e9247aa041b1c260324bf29cee559dd23ba1.tar.gz";
      hash = "sha256-B6jVCeoFjd2H6+7tIses+Kj8DgHS6E2dkVzQAIzDHEc=";
    };
    "gobject-0.3.2-Skun7F6HogCMynX2JqeSHS7xr-8pK4ob-qRFIcEasVi3" = fetchzip {
      name = "gobject";
      url = "https://deps.files.ghostty.org/gobject-2026-07-28-36-1.tar.zst";
      hash = "sha256-dyCfm2XjiAk30zccjD6AgKFBdE7IRsJuoqnscfvnWSQ=";
      nativeBuildInputs = [zstd];
    };
    "N-V-__8AALiNBAA-_0gprYr92CjrMj1I5bqNu0TSJOnjFNSr" = fetchzip {
      name = "gtk4_layer_shell";
      url = "https://deps.files.ghostty.org/gtk4-layer-shell-1.1.0.tar.gz";
      hash = "sha256-UGhFeaBBIfC4ToWdyoX+oUzLlqJsjF++9U7mtszE0y0=";
    };
    "N-V-__8AAG02ugUcWec-Ndp-i7JTsJ0dgF8nnJRUInkGLG7G" = fetchzip {
      name = "harfbuzz";
      url = "https://deps.files.ghostty.org/harfbuzz-11.0.0.tar.xz";
      hash = "sha256-g9jRP85C9XGOKrnjtOgCa+u1WqJsEYC4W3IQjdMkbJ0=";
    };
    "N-V-__8AAGmZhABbsPJLfbqrh6JTHsXhY6qCaLAQyx25e0XE" = fetchzip {
      name = "highway";
      url = "https://deps.files.ghostty.org/highway-66486a10623fa0d72fe91260f96c892e41aceb06.tar.gz";
      hash = "sha256-1xn+WAxeQyrz9KA3y4EOCr5Z94mom7J5TNdippPe2Sw=";
    };
    "N-V-__8AAEbOfQBnvcFcCX2W5z7tDaN8vaNZGamEQtNOe0UI" = fetchzip {
      name = "imgui";
      url = "https://deps.files.ghostty.org/N-V-__8AAEbOfQBnvcFcCX2W5z7tDaN8vaNZGamEQtNOe0UI.tar.gz";
      hash = "sha256-/jVT7+874LCeSF/pdNVTFoSOfRisSqxCJnt5/SGCXPQ=";
    };
    "N-V-__8AAM94BAAFk_hn4UW0x_OBD2g0vOwexeAAyWNNo4eB" = fetchzip {
      name = "iterm2_themes";
      url = "https://deps.files.ghostty.org/ghostty-themes-release-20260921-150923-0b55a9e.tgz";
      hash = "sha256-yJahwqg40oUTTteLWGOjERDo+Cm7mg3e25l7B08a680=";
    };
    "N-V-__8AAIC5lwAVPJJzxnCAahSvZTIlG-HhtOvnM1uh-66x" = fetchurl {
      url = "https://deps.files.ghostty.org/JetBrainsMono-2.304.tar.gz";
      hash = "sha256-xXppHouCrQmLWWPzlZAy5AOPORCHr3cViFulkEYQXMQ=";
    };
    "N-V-__8AAJrvXQCqAT8Mg9o_tk6m0yf5Fz-gCNEOKLyTSerD" = fetchzip {
      name = "libpng";
      url = "https://deps.files.ghostty.org/libpng-1220aa013f0c83da3fb64ea6d327f9173fa008d10e28bc9349eac3463457723b1c66.tar.gz";
      hash = "sha256-Mo1M8TuVaoSIb7Hy2u6zgjZ1DKgpmgNmGRP6dGg/aTs=";
    };
    "libxev-0.0.0-86vtcwIRFADbH4hk-EjROXxlrKIRPQdA41XiTSytYO-F" = fetchzip {
      name = "libxev";
      url = "https://deps.files.ghostty.org/libxev-9ce8e8e6ff89e583258a7f8e7adeeeaeae8611bf.tar.gz";
      hash = "sha256-fOU1oxIxfoEgoLuWz7fVX6M+zmqpo7gqZObWiH/aDE0=";
    };
    "N-V-__8AAG3RoQEyRC2Vw7Qoro5SYBf62IHn3HjqtNVY6aWK" = fetchzip {
      name = "libxml2";
      url = "https://deps.files.ghostty.org/libxml2-2.11.5.tar.gz";
      hash = "sha256-2SEzGhMeIHoHe9EKV6LgPLBXdmrxWWgnLYwUMZFWxNQ=";
    };
    "N-V-__8AAMVLTABmYkLqhZPLXnMl-KyN38R8UVYqGrxqO26s" = fetchurl {
      url = "https://deps.files.ghostty.org/NerdFontsSymbolsOnly-3.4.0.tar.gz";
      hash = "sha256-EWTRuVbUveJI17LwmYxDzJT1ICQxoVZKeTiVsec7DQQ=";
    };
    "N-V-__8AAHjwMQDBXnLq3Q2QhaivE0kE2aD138vtX2Bq1g7c" = fetchzip {
      name = "oniguruma";
      url = "https://deps.files.ghostty.org/oniguruma-1220c15e72eadd0d9085a8af134904d9a0f5dfcbed5f606ad60edc60ebeccd9706bb.tar.gz";
      hash = "sha256-aQdK31CIkzXZel+k8GZt5cv80sTkas9dL28RAVbFheU=";
    };
    "N-V-__8AADYiAAB_80AWnH1AxXC0tql9thT-R-DYO1gBqTLc" = fetchzip {
      name = "pixels";
      url = "https://deps.files.ghostty.org/pixels-12207ff340169c7d40c570b4b6a97db614fe47e0d83b5801a932dcd44917424c8806.tar.gz";
      hash = "sha256-kXYGO0qn2PfyOYCrRA49BHIgTzdmKhI8SNO1ZKfUYEE=";
    };
    "N-V-__8AAKYZBAB-CFHBKs3u4JkeiT4BMvyHu3Y5aaWF3Bbs" = fetchzip {
      name = "plasma_wayland_protocols";
      url = "https://deps.files.ghostty.org/plasma_wayland_protocols-12207e0851c12acdeee0991e893e0132fc87bb763969a585dc16ecca33e88334c566.tar.gz";
      hash = "sha256-iWRv3+OfmHxmeCJ8m0ChjgZX6mwXlcFmK8P/Vt8gDj4=";
    };
    "N-V-__8AAPlZGwBEa-gxrcypGBZ2R8Bse4JYSfo_ul8i2jlG" = fetchzip {
      name = "sentry";
      url = "https://deps.files.ghostty.org/sentry-1220446be831adcca918167647c06c7b825849fa3fba5f22da394667974537a9c77e.tar.gz";
      hash = "sha256-S9fkxLCeQdHOt1FUa8CcZMmORNcxwQSuchng/dNq4g8=";
    };
    "N-V-__8AANb6pwD7O1WG6L5nvD_rNMvnSc9Cpg1ijSlTYywv" = fetchzip {
      name = "spirv_cross";
      url = "https://deps.files.ghostty.org/spirv_cross-1220fb3b5586e8be67bc3feb34cbe749cf42a60d628d2953632c2f8141302748c8da.tar.gz";
      hash = "sha256-7unyC2qPiuyaotRKCVC8HRT+3Kfj9qIxEKVyBlmpMds=";
    };
    "translate_c-0.0.0-Q_BUWhVNBwDOEcIqub4VFPJPB6D9dgwzUMHTX5KWr8Xr" = fetchzip {
      name = "translate_c";
      url = "https://codeberg.org/vancluever/translate-c/archive/4e879eb8aba615de112eabd1231ea6e01920cead.tar.gz";
      hash = "sha256-/sT7W8Kp+O11xaFBgpb/kDiWzfQ0MuXk/d/TuGq1Am8=";
    };
    "uucode-0.2.0-ZZjBPlK5VADj7fdoq7G8LIHzD5o6FSkcBXXrRWr4jnrA" = fetchZigGit {
      name = "uucode";
      url = "https://github.com/jacobsandlund/uucode";
      rev = "2826a37a4562284fdacd8fa029d49509cc9bffcd";
      hash = "sha256-R5RXW5tWIaDq5JOF2+oWd5YOYOyns6WH7f687WE+b20=";
    };
    "uucode-0.2.0-ZZjBPuuFVgC8YZ8eld4fOKsZANLIhTFMzULQxhkLi1C7" = fetchzip {
      name = "uucode";
      url = "https://github.com/jacobsandlund/uucode/archive/9d55524551411b493cca41ca06363625d90aff1e.tar.gz";
      hash = "sha256-KZbp/0dlJc5BdxM19ZOXH74WEjEilTvzie/BjT1aYvw=";
    };
    "vaxis-0.6.0-BWNV_MjFCQCs9UDHiRkrgw_ayeiPkzOe4xVbaAqXkUWW" = fetchZigGit {
      name = "vaxis";
      url = "https://github.com/rockorager/libvaxis.git";
      rev = "c1e1f23be38951c425cdf31af455ba23ef178940";
      hash = "sha256-bIXu8lGwGo42QbItC0jOi/eN7u+f4snknBexw7dc0DI=";
    };
    "vaxis-0.6.0-BWNV_CrbCQCscGpzsAlR402rYQ_tV3aAl081c2iRRkka" = fetchzip {
      name = "vaxis";
      url = "https://deps.files.ghostty.org/vaxis-1dbbe575dff4586fe51e3217aa5c3fecdcbb6089.tar.gz";
      hash = "sha256-z3J3w+oYapfAZZR+MvWXwg+th1hePDA1TptnKFO4r+M=";
    };
    "N-V-__8AAKrHGAAs2shYq8UkE6bGcR1QJtLTyOE_lcosMn6t" = fetchzip {
      name = "wayland";
      url = "https://deps.files.ghostty.org/wayland-9cb3d7aa9dc995ffafdbdef7ab86a949d0fb0e7d.tar.gz";
      hash = "sha256-swXtymMipE7vmifM5HmhXHhxfxBLE66NBAeTcywBiIg=";
    };
    "N-V-__8AAFdWDwA0ktbNUi9pFBHCRN4weXIgIfCrVjfGxqgA" = fetchzip {
      name = "wayland_protocols";
      url = "https://deps.files.ghostty.org/N-V-__8AAFdWDwA0ktbNUi9pFBHCRN4weXIgIfCrVjfGxqgA.tar.gz";
      hash = "sha256-vD7Nj9iLeS52Et3gcX1m9Zmp05A+VV3J3hkPcM11YEQ=";
    };
    "N-V-__8AAKw-DAAaV8bOAAGqA0-oD7o-HNIlPFYKRXSPT03S" = fetchzip {
      name = "wayland_protocols";
      url = "https://deps.files.ghostty.org/wayland-protocols-258d8f88f2c8c25a830c6316f87d23ce1a0f12d9.tar.gz";
      hash = "sha256-93X0dLoCgQcJzjBCBS9YHb4fPVa3wC2lixXcxoLuBtM=";
    };
    "N-V-__8AAP5JWgCGP_AD0teWpa4krRvE9VPZzvviGdbmN4jI" = fetchzip {
      name = "wuffs";
      url = "https://deps.files.ghostty.org/wuffs-7411f488fe2e2c205c3d3b3d28638b7356522930.tar.gz";
      hash = "sha256-sOuwt3R6xG7oqXaA66QGUjFHrEjGnTXjwYs6rSRb+7I=";
    };
    "z2d-0.12.1-j5P_Hsw8EQAKyZTQICCQnAH2xYkLDW8k9uefbsYdfPZ-" = fetchzip {
      name = "z2d";
      url = "https://deps.files.ghostty.org/z2d-7dbae85c81784dba9988320bf9543ed9a81350c8.tar.gz";
      hash = "sha256-Fjr1ORn0ozxU7QY09o2ZOZQHIJsXfVw0UCdZxTKmZJ0=";
    };
    "zf-0.11.0-OIRy8X-RAAAwaRXHMYpj2uvBnuGTZWEE_3V7acqHQNtW" = fetchzip {
      name = "zf";
      url = "https://deps.files.ghostty.org/zf-c35c421f84895193246db06c40683c1a30e616ef.tar.gz";
      hash = "sha256-LHurWwqK8jhP8AZd/CXrMJNeVsKftRCTN31/EgEgKaA=";
    };
    "zig_js-0.0.0-rjCAV7-GAADvMTBL7lPMuvDk7xgS9PCMIZWiOUXLZSlj" = fetchzip {
      name = "zig_js";
      url = "https://deps.files.ghostty.org/zig_js-3c23860e47fdcdc5af805efb7fd0bdac5fd3e9bc.tar.gz";
      hash = "sha256-Q1643wb/MCX0QkPa9QEY9xeQbqpC2IOrjER0ZyL3mH0=";
    };
    "zig_objc-0.0.0-Ir_Sp9gsAQCPAJc0oF5xoWePHWP6Y6tCphDeyNUThJoi" = fetchzip {
      name = "zig_objc";
      url = "https://deps.files.ghostty.org/zig_objc-c8de82ff80281215ad92900866dab7103a8efa8b.tar.gz";
      hash = "sha256-t8cTTJm0crcoGAyOqXO0wB2w7Yit80J2Orwr6prd/G0=";
    };
    "wayland-0.6.0-lQa1kqz8AQADQmdNJsNhLoNHcnEGEUjrOaPV-dtEnEmX" = fetchzip {
      name = "zig_wayland";
      url = "https://deps.files.ghostty.org/wayland-0.6.0-lQa1kqz8AQADQmdNJsNhLoNHcnEGEUjrOaPV-dtEnEmX.tar.gz";
      hash = "sha256-3m/ITNhZUJ/5uD/Tqm+0uZSktGoYgWF5oldOqOCUkIE=";
    };
    "zigimg-0.1.0-8_eo2oyaFwBZwJpmqPkCfVXWBrHcqbYwmrp1I6bTD3lI" = fetchZigGit {
      name = "zigimg";
      url = "https://github.com/zigimg/zigimg";
      rev = "d695acd97c02e57bb151e8f659d1280f5cd6ca70";
      hash = "sha256-0IYATQldT6eJxRR2T/2CsIYZuzomqjvmdVyjmsjguyE=";
    };
    "N-V-__8AAB0eQwD-0MdOEBmz7intriBReIsIDNlukNVoNu6o" = fetchzip {
      name = "zlib";
      url = "https://deps.files.ghostty.org/zlib-1220fed0c74e1019b3ee29edae2051788b080cd96e90d56836eea857b0b966742efb.tar.gz";
      hash = "sha256-TkPLWSN5QcPlL9D0kc/yhH0/puE9bFND24aj5NVDKYs=";
    };
  };

  # The packages whose own manifest declares a dependency by `.path`. Zig
  # 0.16.0 cannot build these through `zig build --system`: it spins in
  # userspace forever, because a `.path` dependency's hash is computed against
  # the system package directory during the fetch and against the real global
  # cache afterwards, and in that mode the two disagree. A package that wants
  # `--system` copies each of these into its build root and passes `--fork=`;
  # see the README.
  pathDependencyPackages = [
  ];
in
  # One directory holding every package the way Zig unpacks it -- filtered by
  # its manifest's `.paths` and checked against its hash -- which is what
  # `zig build --system` wants.
  #
  # They have to be real directories holding real files, not links into each
  # package's own store path. Zig runs a dependency's build steps from inside
  # it and counts its way back out through `..`, which lands in the wrong place
  # when the directory is a symlink; and `installHeadersDirectory` copies only
  # what the directory walk calls a file, so symlinked headers are skipped
  # without a word. Building them all in one derivation gives real files from
  # the start, without a second copy of everything.
  runCommandLocal name
  {
    nativeBuildInputs = [zig_0_16];
    passthru = {inherit pathDependencyPackages;};
  }
  ''
    mkdir "$out"

    # Each package gets a directory of its own to work in, since `zig fetch`
    # leaves what it unpacked in `zig-pkg/` under the directory it ran in.
    unpack() {
      local work="$TMPDIR/work/$1"
      mkdir -p "$work/src" "$work/cache/tmp"
      # workaround https://codeberg.org/ziglang/zig/issues/31866
      # https://github.com/Cloudef/zig2nix/issues/54
      touch "$work/src/build.zig"
      # `zig fetch` recompresses every package into `p/` at gzip level 9 for
      # its own cache, which is nearly all of its time and of no use here.
      # With `p` a file rather than a directory that step fails at once --
      # Zig warns, and carries on -- and the package is left in `zig-pkg/`.
      touch "$work/cache/p"

      local hash
      if ! hash="$(cd "$work/src" && zig fetch --global-cache-dir "$work/cache" "$2" 2>"$work/log")"; then
        cat "$work/log" >&2
        return 1
      fi
      if [ "$hash" != "$1" ]; then
        echo "$2 is $hash to Zig, not $1" >&2
        return 1
      fi
      mv "$work/src/zig-pkg/$1" "$out/$1"
      rm -rf "$work"
    }
    export -f unpack

    # Several at a time: `zig fetch` spends most of a package on one core.
    cores="''${NIX_BUILD_CORES:-0}"
    if [ "$cores" -le 0 ]; then cores="$(nproc)"; fi
    xargs -P "$cores" -n 2 bash -c 'unpack "$@"' unpack <<'EOF'
    ${lib.concatStrings (lib.mapAttrsToList (hash: src: "${hash} ${src}\n") packages)}
    EOF
  ''
